package com.vani.transaction.model;

import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

@Getter
@Setter
@ToString
public class TrVhInfo {
  private String trDt;
  private String orgC;
  private String rlysysId;
  private String svcId;
  private String cliMsgId;
  private String gblid;
  private String pid;
  private String insTm;
  private String rspTm;
  private String trprcStsc;
  private String rspC;
  private String tmoOcuYn;
  private String pvdId;
  private String mctId;
  private String mctNm;
  private String cusLv;
  private String rmtTp;
  private String trfFee;
  private String dcC;
  private String cusTp;
  private String feeTp;
  private String tranDt;
  private String vfyBnk;
  private String vfyMtd;
  private String vfyInf;
  private String chanId;
  private String otp;
  private String otpReqId;
  private String lnkTp;
  private String waltId;
  private String feeIncYn;
  private String prcRec;
  private String tranId;
  private String pri;
  private String debitTp;
  private String debitRsrcNum;
  private String debitNm;
  private String debitAdr;
  private String debitCty;
  private String debitNat;
  private String debitBrcId;
  private String debitBnkId;
  private String curC;
  private String crdEmail;
  private String crdPhno;
  private String crdBnkId;
  private String crdIsuBy;
  private String crdNat;
  private String crdIsuDt;
  private String crdCd;
  private String crdTp;
  private String crdRsrcNum;
  private String crdNm;
  private String crdCty;
  private String tranAm;
  private String tranDesc;
  private String payRefNo;
  private String payRefInf;
  private String addInf;
  private String resTxnC;
  private String vatAm;
  private String bnkRefNo;
  private String sndDt;
  private String wdrAfBiMrk;
  private String wdrAfBi;
  private String bzErrC;
  private String bzErrDesc;
  private String debitPhno;
  private String waltTk;
  private String cusId;
  private String errTp;
  private String errFildLoc;
  private String repRefNo;
  private String otpTp;
  private String isReqOtp2;
  private String authTp;
  private String isBypassOtp;
  private String reqData;
  private String rspData;
  private String etc1;
  private String etc2;
  private String etc3;
  private String lsChgDtm;
  private String lsChgNm;
}
